EXPLODING = 0
DEFUSE = 1
TACOCAT = 2
BEARDCAT = 3
RAINBOWCAT = 4
POTATOCAT = 5
CATTERMELON = 6
ATTACK = 7
FAVOR = 8
NOPE = 9
SHUFFLE = 10
SKIP = 11
SEETHEFUTURE = 12

# Imploding Kittens expansion
IMPLODING = 13
REVERSE = 14
DRAWFROMBOTTOM = 15
FERALCAT = 16
ALTERTHEFUTURE = 17
TARGETTEDATTACK = 18